# Generated by Django 4.2 on 2026-01-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_participant_meetup_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='participant',
            new_name='participants',
        ),
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2024-12-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
