# Generated by Django 4.2 on 2026-01-25 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_remove_meetup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default=datetime.date(2024, 12, 24)),
            preserve_default=False,
        ),
    ]
