# Generated by Django 4.2 on 2026-01-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_rename_participant_meetup_participants_meetup_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='date',
        ),
    ]
