# Generated by Django 4.2.26 on 2025-11-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
