# Generated by Django 4.2.26 on 2025-11-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0008_remove_book_id_alter_book_author_alter_book_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
