# Generated by Django 4.2 on 2025-12-13 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewForm',
            new_name='Review',
        ),
    ]
