# Generated by Django 4.2.26 on 2025-11-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0004_country_book_countries_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='countries_published',
            new_name='published_countries',
        ),
    ]
